name: flutter_ibm_watson
description: The flutter_ibm_watson makes it easy to integrate IBM Watson
version: 0.0.4
homepage: https://github.com/VictorRancesCode/flutter_ibm_watson

dependencies:
  #flutter:
  #  sdk: flutter
  http: ^1.3.0
  http_parser: ^4.1.2
  meta: ^1.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:

environment:
  sdk: '>=2.12.0 <3.0.0'